version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      CxlZmZLKh91D2F0jo5MY6jXmZApov6Hzw8r8W/cWjO2KhLwnah7pMMsAxkzL4tOIFSk+HaqYje+TUdmXr9b885Tr/KTiGpwvmOHDELEbasH8U5jLJUkLAyg3a6H+xo9AGK5oO6DW4DP5+D/P/15m28zOlzbBnrDb73n5GyFmDI8=
